apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim2
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: nginx-webserver
      image: nginx
      volumeMounts:
       - name: webserver-vol01
         mountPath: "/usr/share/nginx/html"
  volumes:
    - name: webserver-vol01
      persistentVolumeClaim:
        claimName: myclaim2