apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume01
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
      path: /var/local/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: nginx-webserver
      image: nginx
      volumeMounts:
       - name: webserver-vol01
         mountPath: "/usr/share/nginx/html"
  volumes:
    - name: webserver-vol01
      persistentVolumeClaim:
        claimName: myclaim