apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  mongoPassw: dGhlcGFzcw==
---
apiVersion: v1
kind: Pod
metadata:
  name: podm
spec:
  containers:
  - name: db
    image: mongo
    env:
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secreteKeyRef:
          name: my-secret
          key: mongoPassw

