apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  selector:
    mylabel: value  
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 7777
    targetPort: 8080



