apiVersion: v1
kind: Service
metadata:
  name: exchange-rate-service
spec:
  selector:
    radixiot.com/app: exchange-rate
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9003
    targetPort: 9002

---

apiVersion: v1
kind: Pod
metadata:
  name: exchange-rate
  labels:
    radixiot.com/app: exchange-rate
spec:
  containers:
  - name: exchange-rate
    image: ghcr.io/shiriuki/exchange-rate:1.0.0
    ports:
    - name: grpc
      containerPort: 9002