apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: counter
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:      
      containers:
      - name: counter
        image: kahootali/counter:1.1
        volumeMounts:
        - name: counter
          mountPath: /app/
        env:
        - name: TEXT
          value: xxx-t      
  volumeClaimTemplates:
  - metadata:
      name: counter
    spec:
      accessModes: 
      - ReadWriteMany
      resources:
        requests:
          storage: 50Mi
      storageClassName: standard